baseURL = "https://cuixiaochen.com/"
languageCode = "en-us"
title = "XiaochenCui's Blog"
theme = "yinyang"

[params]
headTitle = "Xiaochen Cui"
disqus = "cuixiaochen"
favicon = "/favicon.png"

[[params.socials]]
name = "Resume(English)"
link = "https://cuixiaochen.com/resume/resume_english.pdf"

[[params.socials]]
name = "Resume(Chinese)"
link = "https://cuixiaochen.com/resume/resume_chinese.pdf"

[[params.socials]]
name = "Github"
link = "https://github.com/XiaochenCui"

[[params.socials]]
name = "Email"
link = "mailto:jcnlcxc.new@gmail.com"