baseURL = "https://cuixiaochen.com/"
languageCode = "en-us"
title = "XiaochenCui's Blog"
theme = "yinyang"

[params]
headTitle = "Xiaochen Cui"
disqus = "cuixiaochen"
[[params.socials]]
name = "Github"
link = "https://github.com/XiaochenCui"
[[params.socials]]
name = "Email"
link = "mailto://jcnlcxc.new@gmail.com"
